name: Generate and Deploy Snake SVG (Smart)

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build and Deploy Snake
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create dist folder
        run: mkdir -p dist

      - uses: Platane/snk@master
        with:
          github_user_name: SpoonManiac
          github_token: ${{ secrets.GITHUB_TOKEN }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Check for changes
        id: check_changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push changes
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          git commit -m "Update contribution snake [skip ci]"
          git push origin HEAD:main

      - name: Deploy to GitHub Pages
        if: steps.check_changes.outputs.changed == 'true'
        uses: actions/deploy-pages@v1
        with:
          # Caso queira especificar a pasta explicitamente
          source: dist
