name: Generate Datas

on:
  schedule:
    - cron: "0 */12 * * *"  
  workflow_dispatch:

permissions:
  contents: read    
  pages: write      
  id-token: write   

jobs:
  build:
    name: Generate Snake SVG
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      
      - name: Create dist folder
        run: mkdir -p dist

      - uses: Platane/snk@master
        with:
          github_user_name: SpoonManiac
          github_token: ${{ secrets.GITHUB_TOKEN }}
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
